config/routes.rb
Rails.application.routes.draw do
  get 'heartbeat/index'

  get 'marketplace/settings'

  namespace :ebay do
    resource :token, only: [:show] do
      post :request_grant
      get :save_token

      get :start_fetch_legacy_token
    end
    resource :notification, only: [:show]
    resource :location, only: [:edit, :update]
    resource :fulfillment, only: [:edit, :update]
    resource :payment, only: [:create, :edit, :update]
    resource :return, only: [:edit, :update]
    resource :template, only: [:edit, :update]
    resource :usage, only: [:show]

    post 'notification'
  end

  namespace :tcgplayer do
    resource :token, only: [:show, :create]
  end

  namespace :shopify do
    resource :token, only: [:show, :create]

    post 'notification'
  end

  resources :user_card_condition, only: [:index, :update, :show]

  post 'stripe', to: 'stripe#webhook'

  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  get 'product', to: 'static#product'
  get 'pricing', to: 'static#pricing'
  get 'home/index'

  resource :subscription, only: [:show, :update]

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  get '/heartbeat', to: 'heartbeat#index'

  get '/404', to: 'static#not_found'
  get '/500', to: 'static#internal_server_error', as: 'internal_server_error'

  root to: "home#index"
end

app/views/shared/_ebay_tabs.html.erb
<div class="tabs">
  <ul>
    <li<% if local_assigns[:active_tab] == :token %> class="is-active"<% end %>>
      <a href="<%= ebay_token_path %>">
        <span class="icon is-small"><i class="fas <%= @has_ebay ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span>
        <span>API Token</span>
      </a>
    </li>
    <li<% if local_assigns[:active_tab] == :notification %> class="is-active"<% end %>>
      <a <% if @has_ebay %>href="<%= ebay_notification_path %>"<% else %> class="has-text-grey-lighter  "<% end %>>
        <span class="icon is-small"><i class="fas <%= !!(@current_user.user_ebay && @current_user.user_ebay.legacy_auth_token) ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span>
        <span>Ebay Notifications</span>
      </a>
    </li>
    <li<% if local_assigns[:active_tab] == :location %> class="is-active"<% end %>>
      <a <% if @has_ebay %>href="<%= edit_ebay_location_path %>"<% else %> class="has-text-grey-lighter  "<% end %>>
        <span class="icon is-small"><i class="fas <%= !!@ebay_location ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span>
        <span>Location</span>
      </a>
    </li>
    <li<% if local_assigns[:active_tab] == :fulfillment_policy %> class="is-active"<% end %>>
      <a <% if @has_ebay %>href="<%= edit_ebay_fulfillment_path %>"<% else %> class="has-text-grey-lighter  "<% end %>>
        <span class="icon is-small"><i class="fas <%= !!@ebay_fulfillment_policy ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span>
        <span>Fulfillment</span>
      </a>
    </li>
    <li<% if local_assigns[:active_tab] == :payment_policy %> class="is-active"<% end %>>
      <a <% if @has_ebay %>href="<%= edit_ebay_payment_path %>"<% else %> class="has-text-grey-lighter  "<% end %>>
        <span class="icon is-small"><i class="fas <%= !!@ebay_payment_policy_id ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span>
        <span>Payment Policy</span>
      </a>
    </li>
    <li<% if local_assigns[:active_tab] == :return_policy %> class="is-active"<% end %>>
      <a <% if @has_ebay %>href="<%= edit_ebay_return_path %>"<% else %> class="has-text-grey-lighter  "<% end %>>
        <span class="icon is-small"><i class="fas <%= !!@ebay_return_policy ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span>
        <span>Returns</span>
      </a>
    </li>
    <li<% if local_assigns[:active_tab] == :template %> class="is-active"<% end %>>
      <a <% if @has_ebay %>href="<%= edit_ebay_template_path %>"<% else %> class="has-text-grey-lighter  "<% end %>>
        <span class="icon is-small"><i class="fas <%= !!@ebay_template? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span>
        <span>Listing Template</span>
      </a>
    </li>
    <li<% if local_assigns[:active_tab] == :usage %> class="is-active"<% end %>>
      <a href="<%= ebay_usage_path %>">
        <span class="icon is-small"><i class="fas" aria-hidden="true"></i></span>
        <span>Ebay Usage</span>
      </a>
    </li>
  </ul>
</div>

app/views/shared/_marketplace_menu.html.erb
<aside class="menu">
  <p class="menu-label"><strong>EBay</strong></p>
  <ul class="menu-list">
    <li>
      <%= link_to ebay_token_path, class: local_assigns[:active_tab] == :token ? 'is-active' : nil do %>
        <span class="icon is-small"><i class="fas <%= @has_ebay ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span> API Access
      <% end %>
    </li>
    <li>
      <%= link_to ebay_notification_path, class: local_assigns[:active_tab] == :notification ? 'is-active' : nil do %>
        <span class="icon is-small"><i class="fas <%= @has_ebay_legacy_token ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span> API Notifications
      <% end %>
    </li>
    <li>
      <%= link_to edit_ebay_location_path, class: local_assigns[:active_tab] == :location ? 'is-active' : nil do %>
        <span class="icon is-small"><i class="fas <%= @ebay_location ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span> Location
      <% end %>
    </li>
    <li>
      <%= link_to edit_ebay_fulfillment_path, class: local_assigns[:active_tab] == :fulfillment_policy ? 'is-active' : nil do %>
        <span class="icon is-small"><i class="fas <%= @has_ebay_fulfillment_policy ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span> Fulfillment Policy
      <% end %>
    </li>
    <li>
      <%= link_to edit_ebay_payment_path, class: local_assigns[:active_tab] == :payment_policy ? 'is-active' : nil do %>
        <span class="icon is-small"><i class="fas <%= @has_ebay_payment_policy ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span> Payment Policy
      <% end %>
    </li>
    <li>
      <%= link_to edit_ebay_return_path, class: local_assigns[:active_tab] == :return_policy ? 'is-active' : nil do %>
        <span class="icon is-small"><i class="fas <%= @has_ebay_return_policy ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span> Return Policy
      <% end %>
    </li>
    <li>
      <%= link_to 'Custom Listing Template', edit_ebay_template_path, class: local_assigns[:active_tab] == :template ? 'is-active' : nil %>
    </li>
  </ul>
  <p class="menu-label"><strong>Shopify</strong></p>
  <ul class="menu-list">
    <li>
      <%= link_to shopify_token_path, class: local_assigns[:active_tab] == :shopify_token ? 'is-active' : nil do %>
        <span class="icon is-small"><i class="fas <%= @has_shopify ? 'fa-check-square' : 'fa-exclamation-triangle' %>" aria-hidden="true"></i></span> API Access
      <% end %>
    </li>
  </ul>
</aside>