config/routes.rb
Rails.application.routes.draw do
  get 'heartbeat/index'

  get 'marketplace/settings'

  namespace :ebay do
    resource :token, only: [:show] do
      post :request_grant
      get :save_token

      get :start_fetch_legacy_token
    end
    resource :notification, only: [:show]
    resource :location, only: [:edit, :update]
    resource :fulfillment, only: [:edit, :update]
    resource :payment, only: [:create, :edit, :update]
    resource :return, only: [:edit, :update]
    resource :template, only: [:edit, :update]
    resource :usage, only: [:show]

    post 'notification'
  end

  namespace :tcgplayer do
    resource :token, only: [:show, :create]
  end

  namespace :shopify do
    resource :token, only: [:show, :create]

    post 'notification'
  end

  resources :user_card_condition, only: [:index, :update, :show]

  post 'stripe', to: 'stripe#webhook'

  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  get 'product', to: 'static#product'
  get 'pricing', to: 'static#pricing'
  get 'home/index'

  resource :subscription, only: [:show, :update]

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  get '/heartbeat', to: 'heartbeat#index'

  get '/404', to: 'static#not_found'
  get '/500', to: 'static#internal_server_error', as: 'internal_server_error'

  root to: "home#index"
end

app/models/user_card_condition.rb
require 'google/cloud/pubsub'

class UserCardCondition < ApplicationRecord
  belongs_to :user
  belongs_to :card_condition
  has_many :user_card_condition_ebay_api_histories
  has_many :user_card_condition_shopify_api_histories
  has_many :ebay_offers

  has_many :card_condition_price_histories, through: :card_condition

  after_commit :send_change_notification, if: -> { has_ebay_token? || has_shopify_token? }

  private

  def send_change_notification
    Google::Cloud::PubSub.new(
      project_id: 'synkt-1556838469966',
    ).topic('inventory-changed').publish(
      MultiJson.dump(
        user_card_condition_id: self.id,
        user_id: self.user.id,
        quantity: self.quantity,
        price: self.price,
        condition: self.card_condition.condition,
        card_name: self.card_condition.card.name,
        set_name: self.card_condition.card.card_set.name,
      )
    )
  end

  def has_ebay_token?
    self.user.user_ebay && self.user.user_ebay.auth_token && self.user.user_ebay.legacy_auth_token
  end

  def has_shopify_token?
    !!self.user.user_shopify
  end
end

app/controllers/user_card_condition_controller.rb
require 'ebay/client'
require 'http'

class UserCardConditionController < ApplicationController
  include Secured

  before_action :load_ebay_client

  content_security_policy only: :show do |policy|
    policy.script_src :self, :https, :unsafe_inline
  end

  def index
    q = current_user.
      user_card_conditions.
      includes(card_condition: [{card: :card_set}]).
      joins(card_condition: [{card: :card_set}]).
      order("card_sets.released_at desc, regexp_replace(cards.number, '\D', '', 'g')").
      page(params[:page] || 1)

    if !params[:card] || params[:card][:in_stock]
      q = q.where('user_card_conditions.quantity > 0')
    end

    if params[:card] && params[:card][:name] && !params[:card][:name].empty?
      q = q.where('cards.name ~* ?', Regexp.escape(params[:card][:name]))
    end

    if params[:card] && params[:card][:condition] && !params[:card][:condition].empty? && params[:card][:condition] != 'Condition'
      q = q.where('card_conditions.condition = ?', params[:card][:condition])
    end

    if params[:card] && params[:card][:rarity] && !params[:card][:rarity].empty? && params[:card][:rarity] != 'Rarity'
      q = q.where('cards.rarity = ?', params[:card][:rarity])
    end

    if params[:card] && params[:card][:set_id] && params[:card][:set_id] != 'Set'
      q = q.where('card_sets.id = ?', params[:card][:set_id])
    end

    @user_card_conditions = q.all

    @card_sets = CardSet.where.not(released_at: nil).order(released_at: :desc).all + 
      CardSet.where(released_at: nil).order(name: :asc).all

    @conditions = [
      'near-mint',
      'slightly-played',
      'heavily-played',
      'foil-near-mint',
      'foil-slightly-played',
      'foil-heavily-played',
    ]

    @rarities = [
      'common',
      'uncommon',
      'rare',
      'mythic',
    ]
  end

  def show
    @user_card_condition = current_user.user_card_conditions.includes(card_condition: [{card: :card_set}]).find_by_id(params[:id])

    unless @user_card_condition
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def update
    current_user.
      user_card_conditions.
      where(id: params[:id]).
      update(quantity: params[:user_card_condition][:quantity], price: (params[:user_card_condition][:price].to_f * 100).to_i)
  end

  private

  def load_ebay_client
    return unless current_user.user_ebay

    @ebay_client = Ebay::Client.new(
      Rails.configuration.ebay['base_url'],
      current_user.user_ebay.method(:current_token),
      Rails.configuration.ebay,
      HTTP.use(logging: {logger: Rails.logger}),
    )

    @has_ebay = current_user.valid_ebay_token
  end
end

app/helpers/user_card_condition_helper.rb
module UserCardConditionHelper
end

app/views/user_card_condition/index.html.erb
<% title "Manage Your Inventory" %>
<section class="section">
  <div class="container">
    <h1 class="title">Your card inventory</h1>
    <% if !(@current_user.user_ebay && @current_user.user_ebay.auth_token && @current_user.user_ebay.legacy_auth_token) && !@current_user.user_shopify %>
      <p class="notification is-danger" style="margin-bottom: 1rem;">
        You haven't setup your marketplace settings, so none of your inventory will sync. <%= link_to 'Setup your marketplace settings now.', marketplace_settings_path %>
      </p>
    <% end %>
    <%= form_with method: :get, class: 'search', local: true do |form| %>
      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field is-narrow">
            <p class="control">
              <%= text_field_tag('card[name]', params.fetch(:card, {})[:name], class: 'input', placeholder: 'Card Name') %>
            </p>
          </div>
          <div class="field is-narrow">
            <div class="control">
              <div class="select">
                <%= select_tag('card[set_id]', options_for_select(['Set'] + @card_sets.map { |cs| [cs.name, cs.id] }, selected: params.fetch(:card, {}).fetch(:set_id, 'Set'))) %>
              </div>
            </div>
          </div>
          <div class="field is-narrow">
            <div class="control">
              <div class="select">
                <%= select_tag('card[condition]', options_for_select(['Condition'] + @conditions, selected: params.fetch(:card, {}).fetch(:condition, 'Condition'))) %>
              </div>
            </div>
          </div>
          <div class="field is-narrow">
            <div class="control">
              <div class="select">
                <%= select_tag('card[rarity]', options_for_select(['Rarity'] + @rarities, selected: params.fetch(:card, {}).fetch(:rarity, 'Rarity'))) %>
              </div>
            </div>
          </div>
          <div class="field is-narrow">
            <div class="control">
              <label class="checkbox">
                <input type="checkbox" name="card[in_stock]">
                In Stock Only
              </label>
            </div>
          </div>
          <div class="field is-narrow">
            <div class="control">
              <button class="button is-link">
                Search
              </button>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%= paginate @user_card_conditions, window: 10 %>
    <div class="table is-striped is-fullwidth">
      <div class="table-header">
        <div>Card Name</div>
        <div>Set Name</div>
        <div>Condition</div>
        <div>Rarity</div>
        <div>Quantity</div>
        <div>Price</div>
        <div>Market</div>
        <div>Save</div>
      </div>
      <% @user_card_conditions.each do |ucc| %>
        <%= form_with model: ucc, class: :items, method: :patch, data: { controller: 'user-card-condition--index' } do |form| %>
          <div><%= link_to(ucc.card_condition.card.name, user_card_condition_path(ucc)) %></div>
          <div><%= ucc.card_condition.card.card_set.name %></div>
          <div><%= ucc.card_condition.condition %></div>
          <div><%= ucc.card_condition.card.rarity %></div>
          <div class="quantity">
            <%= form.text_field :quantity, type: :number, class: :input, value: ucc.quantity, data: { target: 'user-card-condition--index.quantity', action: 'keyup->user-card-condition--index#quantityChange' } %>
          </div>
          <div class="price">
            <%= form.text_field :price, class: :input, value: '%.2f' % (ucc.price / 100.0), data: { target: 'user-card-condition--index.price', action: 'keyup->user-card-condition--index#priceChange' } %>
          </div>
          <div class="price">
            <%= ucc.card_condition.latest_price %>
          </div>
          <div class="save">
            <%= form.submit 'Save', class: 'button is-primary', data: { disable_with: 'Saving...', target: 'user-card-condition--index.submit' } %>
          </div>
        <% end %>
      <% end %>
    </div>
    <%= paginate @user_card_conditions, window: 10 %>
    <% if @user_card_conditions.length == 0 %>
      <div class="content">
        <p>You have no inventory saved. Use the search box above to search for cards to add to your inventory!</p>
        <p>Need help? Check out our <a href="https://synkt.freshdesk.com/support/solutions/articles/47000450159-creating-your-first-sync" target="_blank">help page on creating your first sync</a>.</p>
      </div>
    <% end %>
  </div>
</section>

app/views/user_card_condition/show.html.erb
<% title "Manage #{@user_card_condition.card_condition.card.name} / #{@user_card_condition.card_condition.card.card_set.name}" %>
<section class="section">
  <div class="container" data-controller="user-card-condition--show">
    <div class="columns">
      <div class="column is-one-quarter">
        <figure class="image is-2x3">
          <img src="<%= @user_card_condition.card_condition.card.image_url %>" alt="<%= @user_card_condition.card_condition.card.name %>">
        </figure>
      </div>
      <div class="column is-one-quarter">
        <h1 class="title"><%= @user_card_condition.card_condition.card.name %></h1>
        <h2 class="subtitle"><%= @user_card_condition.card_condition.card.card_set.name %></h2>
        <h3 class="subtitle"><%= @user_card_condition.card_condition.card.rarity %></h3>
        <h3 class="subtitle"><%= @user_card_condition.card_condition.condition %></h3>
        <%= form_with model: @user_card_condition, method: :patch do |form| %>
          <div class="field">
            <label class="label">Quantity</label>
            <div class="control">
              <%= form.text_field :quantity, class: :input %>
            </div>
          </div>
          <div class="field">
            <label class="label">Price</label>
            <div class="control">
              <%= form.text_field :price, class: :input, value: '%.2f' % (@user_card_condition.price / 100.0) %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= form.submit 'Save', class: 'button is-primary', 'data-disable-with': 'Saving...' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="column">
        <h2 class="title is-3">Market Price History</h2>
        <%= line_chart @user_card_condition.card_condition_price_histories.map { |h| [h.date.strftime("%Y-%m-%d"), h.price / 100.0] }, points: false %>
      </div>
    </div>
    <div class="tabs is-large is-boxed">
      <ul>
        <li data-target="user-card-condition--show.ebayButton" class="is-active"><a data-action="user-card-condition--show#showEbay">eBay Activity</a></li>
        <li data-target="user-card-condition--show.shopifyButton"><a data-action="user-card-condition--show#showShopify">Shopify Activity</a></li>
      </ul>
    </div>

    <div class="box" data-target="user-card-condition--show.ebay">
      <% if @user_card_condition.ebay_offers.count > 0 %>
        <h2 class="title is-3">Ebay Listing Links</h1>
        <div class="tabs is-toggle is-medium">
          <ul>
            <% @user_card_condition.ebay_offers.where.not(listing_id: nil).each do |eo| %><li><a href="https://ebay.com/itm/<%= eo.listing_id %>" target="_blank"><%= eo.quantity %>x: <%= eo.listing_id %></a></li><% end %>
          </ul>
        </div>
      <% end %>
      <h2 class="title is-3">Ebay API History</h1>
      <% @user_card_condition.user_card_condition_ebay_api_histories.order(created_at: :desc).limit(10).each do |h| %>
        <div class="box is-clipped">
          <table class="table">
            <tbody>
              <tr>
                <td>At</td>
                <td><%= h.created_at %></td>
              </tr>
              <tr>
                <td>Interaction Type</td>
                <td><%= h.interaction_type%></td>
              </tr>
              <tr>
                <td>Request</td>
                <td><%= h.api_request%></td>
              </tr>
              <tr>
                <td>Response</td>
                <td><%= h.api_response%></td>
              </tr>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>

    <div class="box is-hidden" data-target="user-card-condition--show.shopify">
      <h2 class="title is-3">Shopify API History</h1>
      <% @user_card_condition.user_card_condition_shopify_api_histories.order(created_at: :desc).limit(10).each do |h| %>
        <div class="box is-clipped">
          <table class="table">
            <tbody>
              <tr>
                <td>At</td>
                <td><%= h.created_at %></td>
              </tr>
              <tr>
                <td>Interaction Type</td>
                <td><%= h.interaction_type%></td>
              </tr>
              <tr>
                <td>Request</td>
                <td><%= h.api_request%></td>
              </tr>
              <tr>
                <td>Response</td>
                <td><%= h.api_response%></td>
              </tr>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</section>