config/routes.rb
Rails.application.routes.draw do
  get 'heartbeat/index'

  get 'marketplace/settings'

  namespace :ebay do
    resource :token, only: [:show] do
      post :request_grant
      get :save_token

      get :start_fetch_legacy_token
    end
    resource :notification, only: [:show]
    resource :location, only: [:edit, :update]
    resource :fulfillment, only: [:edit, :update]
    resource :payment, only: [:create, :edit, :update]
    resource :return, only: [:edit, :update]
    resource :template, only: [:edit, :update]
    resource :usage, only: [:show]

    post 'notification'
  end

  namespace :tcgplayer do
    resource :token, only: [:show, :create]
  end

  namespace :shopify do
    resource :token, only: [:show, :create]

    post 'notification'
  end

  resources :user_card_condition, only: [:index, :update, :show]

  post 'stripe', to: 'stripe#webhook'

  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  get 'product', to: 'static#product'
  get 'pricing', to: 'static#pricing'
  get 'home/index'

  resource :subscription, only: [:show, :update]

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  get '/heartbeat', to: 'heartbeat#index'

  get '/404', to: 'static#not_found'
  get '/500', to: 'static#internal_server_error', as: 'internal_server_error'

  root to: "home#index"
end

app/controllers/ebay/fulfillments_controller.rb
require 'ebay/error'
require 'ebay/policy'
require 'ebay/decorators/fulfillment'

module Ebay
  class FulfillmentsController < ApplicationController
    include MarketplaceData

    def edit
      @policies = @ebay_client.get_fulfillment_policies[:fulfillmentPolicies].map { |p| [p[:name], p[:fulfillmentPolicyId]] }
      @policy_id = current_user.user_ebay.fulfillment_policy_id
    end

    def update
      current_user.user_ebay.update!(
        fulfillment_policy_id: params[:policy_id],
      )
    end
  end
end

app/controllers/ebay/locations_controller.rb
require 'ebay/client'
require 'http'

module Ebay
  class LocationsController < ApplicationController
    include MarketplaceData

    before_action :load_location, only: [:update]

    def edit
      location = Struct.new(
        :street,
        :building,
        :city,
        :state_or_province,
        :postal_code,
        :country,
      )

      @inventory_location = if @ebay_location
        location.new(
          @ebay_location[:location][:address][:addressLine1],
          @ebay_location[:location][:address][:addressLine2],
          @ebay_location[:location][:address][:city],
          @ebay_location[:location][:address][:stateOrProvince],
          @ebay_location[:location][:address][:postalCode],
          'US',
        )
      else
        location.new
      end
    end

    def update
      Ebay::Client.new(
        Rails.configuration.ebay['base_url'],
        current_user.user_ebay.method(:current_token),
        Rails.configuration.ebay,
        HTTP.use(logging: {logger: Rails.logger}),
      ).create_location(
        current_user.id,
        Struct.new(
          :street,
          :building,
          :city,
          :state_or_province,
          :postal_code,
          :country,
        ).new(
          params[:street],
          params[:building],
          params[:city],
          params[:state_or_province],
          params[:postal_code],
          'US',
        ),
      )
    rescue Ebay::Error => e
      render :json => MultiJson.dump(
        code: e.code,
        message: e.message,
      ), status: 400
    end
  end
end

app/controllers/ebay/notifications_controller.rb
module Ebay
  class NotificationsController < ApplicationController
    include MarketplaceData

    def show; end
  end
end

app/controllers/ebay/payments_controller.rb
require 'ebay/error'

module Ebay
  class PaymentsController < ApplicationController
    include MarketplaceData

    def edit
      @policies = @ebay_client.get_payment_policies[:paymentPolicies].map { |p| [p[:name], p[:paymentPolicyId]] }
      @policy_id = current_user.user_ebay.payment_policy_id
    end

    def update
      current_user.user_ebay.update!(
        payment_policy_id: params[:policy_id],
      )
    end
  end
end

app/controllers/ebay/returns_controller.rb
module Ebay
  class ReturnsController < ApplicationController
    include MarketplaceData

    def edit
      @policies = @ebay_client.get_return_policies[:returnPolicies].map { |p| [p[:name], p[:returnPolicyId]] }
      @policy_id = current_user.user_ebay.return_policy_id
    end

    def update
      current_user.user_ebay.update!(
        return_policy_id: params[:policy_id],
      )
    end
  end
end

app/controllers/ebay/templates_controller.rb
module Ebay
  class TemplatesController < ApplicationController
    include MarketplaceData

    def edit
    end

    def update
      if params[:template] && !params[:template].empty?
        current_user.user_ebay.update(template: params[:template])
      end
    end
  end
end

app/controllers/ebay/tokens_controller.rb
require 'http'

module Ebay
  class TokensController < ApplicationController
    include MarketplaceData

    def show; end

    def request_grant
      redirect_to "#{Rails.configuration.ebay['auth_url']}/oauth2/authorize?"+
        "client_id=#{Rails.configuration.ebay['client_id']}&"+
        "response_type=code&"+
        "redirect_uri=#{Rails.configuration.ebay['ru_name']}&"+
        "scope=#{URI.escape(Ebay::Client.auth_scopes)}"
    end

    def start_fetch_legacy_token
      session_id = @ebay_client.get_session_id

      session[:ebay_session_id] = session_id

      redirect_to "https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&"+
        "runame=#{Rails.configuration.ebay['ru_name']}"+
        "&SessID=#{session_id}"
    end

    def save_token
      if params[:code] # oauth2
        resp = HTTP.use(logging: {logger: Rails.logger}).basic_auth(
          user: Rails.configuration.ebay['client_id'],
          pass: Rails.configuration.ebay['client_secret'],
        ).post(
          "#{Rails.configuration.ebay['base_url']}/identity/v1/oauth2/token",
          form: {
            grant_type: :authorization_code,
            redirect_uri: Rails.configuration.ebay['ru_name'],
            code: params[:code],
          },
        )

        if resp.code == 200
          body = MultiJson.load(resp.to_s)

          current_user.user_ebay = UserEbay.create!(
            user_id: current_user.id,
            auth_token: body['access_token'],
            auth_token_expires_at: Time.now + body['expires_in'],
            refresh_token: body['refresh_token'],
            refresh_token_expires_at: Time.now + body['refresh_token_expires_in'],
          )

          redirect_to ebay_token_path
        end
      else # auth n auth
        token, expires_at = @ebay_client.fetch_token(session[:ebay_session_id])

        current_user.user_ebay.update!(
          legacy_auth_token: token,
          legacy_auth_token_expires_at: expires_at,
        )

        Ebay::Client.new(
          Rails.configuration.ebay['base_url'],
          current_user.user_ebay.method(:current_token),
          Rails.configuration.ebay,
          HTTP.use(logging: {logger: Rails.logger}),
        ).set_notification_preferences("https://web-uaexzjfedq-uc.a.run.app#{ebay_notification_path}", token)

        Ebay::Client.new(
          Rails.configuration.ebay['base_url'],
          current_user.user_ebay.method(:current_token),
          Rails.configuration.ebay,
          HTTP.use(logging: {logger: Rails.logger}),
        ).set_out_of_stock(token)

        redirect_to ebay_notification_path
      end
    end
  end
end

app/controllers/ebay/usages_controller.rb
module Ebay
  class UsagesController < ApplicationController
    include MarketplaceData

    def show
      p = @ebay_client.get_privilege
      @ebay_selling_stats = if p[:sellingLimit]
                              {
                                value: p[:sellingLimit][:amount][:value].to_i,
                                max: p[:sellingLimit][:quantity].to_i,
                              }
                            else
                              {
                                value: 'Unknown',
                                max: 'Unknown',
                              }
                            end
    end
  end
end

app/controllers/ebay_controller.rb
require 'ebay/parse_item_transactions'

class EbayController < ActionController::Base 
  skip_before_action :verify_authenticity_token

  def notification
    transaction_id, item_id, quantity_purchased = Ebay::ParseItemTransactions.call(request.raw_post)

    # FIXME: verify post is from ebay: https://developer.ebay.com/DevZone/guides/ebayfeatures/Notifications/Notifications.html#SOAPMessageHeaderNotificationSignature

    if transaction_id && item_id && quantity_purchased
      eo = EbayOffer.find_by_listing_id(item_id)
      if eo
        ucc = eo.user_card_condition
        ucc.quantity -= quantity_purchased * eo.quantity
        ucc.save!

        EbayTransactionHistory.create!(
          user_card_condition: ucc,
          quantity: quantity_purchased,
          transaction_id: transaction_id,
          xml: request.raw_post,
        )
      end
    end

    head :ok
  end
end

app/helpers/ebay_helper.rb
module EbayHelper
end

app/views/ebay/locations/edit.html.erb
<% title "Ebay Marketplace Settings - Ebay Inventory Location" %>

<% content_for :javascript do %>
  <%= javascript_pack_tag 'ebay_location_edit' %>
<% end %>

<div class="container">
  <div class="columns">
    <div class="column is-3">
      <%= render 'shared/marketplace_menu', active_tab: :location %>
    </div>
    <div class="column">
      <h2 class="subtitle">Location</h2>
      <% if !@current_user.user_ebay %>
        <p>Please setup your API Token using the menu before setting up your location.</p>
      <% else %>
        <% if !@ebay_location %>
          <p>Ebay requires each listing to be associated with an inventory location. This should be your primary address that you ship inventory from.</p>
          <p>We only support accounts based in the USA currently.</p>
        <% else %>
          <p>Your Ebay inventory location has been saved. It cannot be changed once saved.</p>
        <% end %>
        <%= form_with url: ebay_location_path, html: { method: :patch, disabled: !!@ebay_location } do |f| %>
          <fieldset class="box"<% if !!@ebay_location %> disabled<% end %>>
            <div class="field">
              <label class="label">Street</label>
              <div class="control">
                <%= f.text_field :street, value: @inventory_location.street, class: 'input' %>
              </div>
            </div>
            <div class="field">
              <label class="label">Building</label>
              <div class="control">
                <%= f.text_field :building, value: @inventory_location.building, class: 'input' %>
              </div>
            </div>
            <div class="field">
              <label class="label">City</label>
              <div class="control">
                <%= f.text_field :city, value: @inventory_location.city, class: 'input' %>
              </div>
            </div>
            <div class="field">
              <label class="label">State or Province</label>
              <div class="control">
                <%= f.text_field :state_or_province, value: @inventory_location.state_or_province, class: 'input' %>
              </div>
            </div>
            <div class="field">
              <label class="label">Postal Code</label>
              <div class="control">
                <%= f.text_field :postal_code, value: @inventory_location.postal_code, class: 'input' %>
              </div>
            </div>
            <div class="field">
              <label class="label">Country</label>
              <div class="control">
                <%= f.text_field :country, value: @inventory_location.country, class: 'input' %>
              </div>
            </div>
            <% if !@ebay_location %><div class="field">
              <div class="control">
                <button type="submit" class="button is-link">Save</button>
              </div>
            </div><% end %>
          </fieldset>
        <% end %>
      <% end %>
    </div>
  </div>
</div>